### ISSUE TITLE
Cerberus Sign-up Walkthrough

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mycroft-core-documentation#10]
Walk-through step-by-step of pairing device.

**Comment by ethanaward** [comment]
I know we were talking about making Cerberus not dependent on a Google account anymore, since some people might have issues with that. Do we want to make this walkthrough after we make that change, since the process/some potential screenshots might change? Or should we make one now and then update it later as needed?

**Comment by ryanleesipes** [comment]
Let's make it now, and then put something like "We are working to support other authentication methods, please stay tuned for updates to allow that."

**Comment by ethanaward** [comment]
Sounds good.

**Comment by ryanleesipes** [comment]
v1 looks great, thanks @ethanaward
